name: Deploy static content to Pages
on:
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Adjust src dir
        run: |
          mkdir -pv http/elden-ring
          cp -v src/* http/elden-ring/
          cp -v checklists/elden-ring.yaml http/elden-ring/checklist.yaml

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "http"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
